### ISSUE TITLE
Solid background behind OSD text

### ISSUE THREAD

**Issue by ned-kelly** [dzen/pyosd#1]
Is there any way that we can add a solid background on the OSD text?

Sometimes it's a bit hard to read (i.e. White text with white picture behind it) so I'd love to be able to add a solid black background - just behind the OSD text (say with a 5 or 10px padding).

Cheers,

**Comment by dzen** [comment]
Hello,

this isn't the official repo, just a quick projet to help a friend with python3 on pyosd.
